version: '3.8'

services:
  db-dev:
    image: postgres:latest
    container_name: dev-db
    ports:
      - "5434:5432"
    
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data:
